### ISSUE TITLE
Add S3-syncing for change of package hosting

### ISSUE THREAD

**Issue by sirosen** [globus/globus-release-tools#2]
This was planned in globusonline/go-ops#32

Because we're moving the hosting of the managed packages into S3, we need a syncing script which moves content to S3 from the local cache.

Rather than trying to operate against the uploaded content (potentially tricky), this is going to be a simple `boto3` python script which sync from the local cache dir to `unstable`, `testing`, and `stable` as specified by the caller.

**Comment by sirosen** [comment]
When I look at the [current GT6 dir](http://toolkit.globus.org/ftppub/gt6/), I see several dirs like the `installers` dir as well, which I'll have to handle.

I'm going to start by writing `s3_upload_dir(source_dir, bucket_name, dest_dir)` using `os.walk` (slow, but guaranteed to work), and see where I can take it from there.
At the very least it should be a reusable component.

**Comment by sirosen** [comment]
@bester I have several questions about this script.
1. How do I generate docs?
   I see documentation in several places as HTML and TXT docs plus manpages, and I assume there's some toolchain at play for compiling that content from a single source.
   I'm happy to write up docs on this, especially since it's pretty simple, so long as I can learn how. :smile: 
   Or we could leave this out of those docs for now and rely on `--help`.
2. Is the currently available tuning which I have sufficient?
   Right now you can crudely tune the parallelism by adjusting the size of the thread pool used, and you can adjust how we check whether or not to upload files (checksum, mtime, size, always upload). Is there anything more we think might be necessary? Anything more you would want out of this?
3. Do you need deletion / introspection capabilities beyond the abilities of the awscli?
   You can manually interact with the bucket with the awscli in addition to this handy-dandy script, which covers any unplanned needs or unusual conditions. However, are there S3-syncing operations other than uploading files which should be supported?
4. Where should I put the credentials for accessing this bucket?
   Is there a good place to store the AWS key and secret?

This is very close -- it might be ready for review now, assuming none of the above indicate a need for further work.

**Comment by sirosen** [comment]
Oh, for convenience, the GitHub link to the current version of the script:
https://github.com/globus/globus-release-tools/blob/s3-repo-tools/bin/repo-s3-sync

**Comment by bester** [comment]
1. The .txt files are asciidoc. They change rarely, so I had been manually dumping the output of 

```
a2x -d manpage -f manpage name.txt
```

to the man directory
2. That sounds like more than enough knobs. The build process doesn't like to publish a changed package without a file name change, so it should mainly be only the small number of metadata files that will actually be replaced. The changes that will be uploaded at any time will typically be on order of dozens of files.
3. I haven't ever deleted a package from the repository, so I don't think anything like that is pressing.
4. That's a good question. I'm not sure where we will be running this anyway (does it belong on builds.globus.org?).

**Comment by sirosen** [comment]
> The .txt files are asciidoc...

Good to hear. I'll get some docs into the current work in progress branch.

> That sounds like more than enough knobs...

Music to my ears. :notes:
There's an option to specify which subdir (relative to the package data root) is being uploaded. Will that be easy enough to do small, file-oriented updates?

It was more tuning than I originally planned, but single-threaded and fully synchronous processing was, predictably, very slow.

> I haven't ever deleted a package from the repository...

And using this script, you never will! :stuck_out_tongue: 
Good to know it's not a need.

> That's a good question. I'm not sure where we will be running this anyway (does it belong on builds.globus.org?).

`builds.globus.org` sounds like a reasonable place.
Right now the default root dir for package data is, like the other scripts, `repo.default_root`, which seems tuned to running on the MCS machine.
Maybe we start tweaking defaults on everything at a later stage.

**Comment by sirosen** [comment]
I've added credentials to `builds.globus.org` under the description "S3://downloads.globus.org/data/toolkit/ Credentials"

Is there more work on Jenkins that I should be doing to assist? Those credentials will need to be in the environment for this script somehow, so maybe putting them directly on disk (rather than in Jenkins config) would be better?

**Comment by sirosen** [comment]
Need to look into setting mimetype on files.

If CloudFront can do it for us, that would be great.
Otherwise, we'll have to consider whether or not we want to extend the sync tool in #3 to set it explicitly on every file.
